STATUS_OPEN_LOWER = 'open'
STATUS_OPEN_CAPITALIZE = 'Open'

STATUS_CLOSE_LOWER = 'closed'
STATUS_CLOSE_CAPITALIZE = 'Closed'

STATUS_CHOICES = [
        (STATUS_OPEN_LOWER, STATUS_OPEN_CAPITALIZE),
        (STATUS_CLOSE_LOWER, STATUS_CLOSE_CAPITALIZE)
    ]

TEST_USER_LOGIN = 'owner@test.com'
TEST_USER_PASSWORD = '12345'
TEST_USER_NAME = 'Test'
TEST_USER_SURNAME = 'Owner'

TEST_USER_OTHER_LOGIN = 'other@test.com'
TEST_USER_OTHER_NAME = 'Other'

TEST_PROJECT_NAME = 'Test Project'
TEST_PROJECT_DESCRIPTION = 'Description'

MAX_LENGTH_NAME = 200
MAX_LENGTH_STATUS = 6

PAGINATE = 12
